# Generated by Django 3.1 on 2020-09-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('student_number', models.IntegerField(default=0)),
                ('member_name', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('dob', models.DateField()),
                ('is_committee', models.BooleanField(default=False, null=True)),
                ('pronouns', models.CharField(max_length=25)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='member_details',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('active_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memapp.member_info')),
            ],
        ),
    ]
