# Generated by Django 3.1 on 2020-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memapp', '0002_auto_20200911_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_info',
            name='user_n',
            field=models.CharField(default='', max_length=50),
        ),
    ]
