# Generated by Django 3.1 on 2020-09-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memapp', '0003_member_info_user_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_info',
            old_name='user_n',
            new_name='user_name',
        ),
    ]
