# Generated by Django 3.1 on 2020-09-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memapp', '0004_auto_20200914_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_info',
            old_name='user_name',
            new_name='username',
        ),
    ]
