# Generated by Django 3.1 on 2020-09-14 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('pub_notes', models.TextField(blank=True)),
                ('priv_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('child_tag', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='edge_child', to='libapp.tag')),
                ('parent_tag', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='edge_parent', to='libapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('implied', models.IntegerField(default=0)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.asset')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.tag')),
            ],
        ),
    ]
