# Generated by Django 3.1 on 2020-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='libapp.Tag'),
        ),
    ]
